# Site settings
title: License translations
email: launois.maxime@free.fr
description: >- # this means to ignore newlines until "baseurl:"
  Translating the most commonly used licenses.
baseurl: ""
url: "https://mlaunois.github.io/license-translations"
github_username:  license-translations
repository: license-translations/license-translations.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
sass:
    style: compressed
collections:
  apache:
    output: true
  fsf:
    output: true
  bsd-like:
    output: true
  about:
    output: true
  mit:
    output: true
  show-license:
    output: true
  tools:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
